package opcode

import (
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

//nolint:gochecknoglobals // NotLogCP must be set as a global variable to skip debugging
var NotLogCP = map[uint16]bool{
	CP_AliveAck: true,
	CP_UserMove: true,
	CP_MobMove:  true,
	CP_NpcMove:  true,
}

//nolint:gochecknoglobals // NotLogLP must be set as a global variable to skip debugging
var NotLogLP = map[uint16]bool{
	LP_AliveReq: true,
	LP_UserMove: true,
	LP_MobMove:  true,
	LP_NpcMove:  true,
}

func GenOpcodeMap(originPath, targetPath, mapName string) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, originPath, nil, parser.AllErrors)
	if err != nil {
		panic(err)
	}
	out, err := os.Create(targetPath)
	if err != nil {
		panic(err)
	}
	defer func() {
		err = out.Close()
		if err != nil {
			panic(err)
		}
	}()
	_, _ = fmt.Fprintln(out, "// Code generated by opcode_test, DO NOT EDIT.")
	_, _ = fmt.Fprintln(out, "package opcode")
	_, _ = fmt.Fprintf(out, "\nvar %s map[uint16]string = map[uint16]string{", mapName)
	_, _ = fmt.Fprintln(out, "")
	ast.Inspect(f, func(n ast.Node) bool {
		v, ok := n.(*ast.ValueSpec)
		if !ok {
			return true
		}
		for _, name := range v.Names {
			var lit *ast.BasicLit
			lit, ok = v.Values[0].(*ast.BasicLit)
			if !ok {
				panic(errors.New("failed to assert *ast.BasicLit"))
			}
			var value int64
			value, err = strconv.ParseInt(lit.Value, 0, 16)
			if err != nil {
				panic(err)
			}
			_, _ = fmt.Fprintf(out, "\t0x%X: \"%s\",\n", value, name.Name)
		}
		return true
	})
	_, _ = fmt.Fprintln(out, "}")
}
